### ISSUE TITLE
Argon Pro React?

### ISSUE THREAD

**Issue by knittycatkitty** [creativetimofficial/argon-dashboard-react#1]
Hi are you making a React version for the Argon Pro?

**Comment by einazare** [comment]
Hello there @knittycatkitty ,

Thank you for your interest in working with our product.
The development for the PRO version is starting today, and we expect to take us around 3 weeks to release it. We'll do all we can to release it sooner.

Best,
Manu

**Comment by knittycatkitty** [comment]
I see it! woo
