### ISSUE TITLE
Argon Layouts Like Documentation Web ?

### ISSUE THREAD

**Issue by bakerstreetatpku** [creativetimofficial/argon-dashboard-react#13]
Hi there,
I'm a newborn react programmer. just hatched from my php egg's shell so this is a very new stuff for me. 

I'd like to ask you about the [documentation's layout](https://demos.creative-tim.com/argon-dashboard-react/#/documentation/overview). is there any tutorial to make a layout like that ? 

Here's what i need : 
- I want a persistent / fixed navbar on top, 
- a sticky bar above the navbar (if scrolled this bar is covered by the navbar while the navbar is fixed)
- a sidebar on the left side below the top navbar
- a footer below the sidebar and content of view.

If you have any clue about how i am suppose to do or where should i begin or maybe a link with similar topic i'll be very grateful. coz i haven't found the result i'm looking for when i was googling about Argon. feels like i'm walking around the desert without knowing where i have to go.

Many Thanks before.

**Comment by einazare** [comment]
Hello there, @bakerstreetatpku ,

Thank you for your interest in working with our products.
You can add the following css code after all of our css codes and imports:
```
.main-content .navbar-top{
   position: fixed !important;
   background-color: #172b4d!important;
}
.main-content, .navbar-vertical{
   margin-top: 82px !important;
}
```
This should do the trick.
Also, please, next time follow our rules:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/argon-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

Best,
Manu

**Comment by bakerstreetatpku** [comment]
Thanks a lot @EINazare 
I'll try it out later and sorry for not following the rule coz at first I didn't really catch what's the rule mean. But now i get it. 

btw i have found something interesting when i was strugling with Reactstrap. I just found out that there's some classes to ease our way on styling anything on element such as pt mt py etc. I guess i'm gonna start with that before i'm messing with css code ^_^.

Thanks again
