### ISSUE TITLE
[Bug] error trying to start project with npm start

### ISSUE THREAD

**Issue by pmacs-carlomagnorocha** [creativetimofficial/argon-dashboard-react#15]
### Version
 latest version available at https://www.creative-tim.com/product/argon-dashboard-react?tracking=first-time#
### Operating System
windows 10
### Device
PC
### Browser & Version
Chrome 78.0.3904.108 64 bits
### Steps to reproduce
1 - npm install
2 - npm start
### What is expected?
The application starts
### What is actually happening?
When I try to start the application the following error occurs: 
./src/assets/scss/argon-dashboard-react.scss (./node_modules/css-loader??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/assets/scss/argon-dashboard-react.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
Require stack:
- C:\Users\andre.rocha\Desktop\CIDACS_PAMACS\React\argon-dashboard-react-master\node_modules\sass-loader\lib\loader.js
- C:\Users\andre.rocha\Desktop\CIDACS_PAMACS\React\argon-dashboard-react-master\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\andre.rocha\Desktop\CIDACS_PAMACS\React\argon-dashboard-react-master\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\andre.rocha\Desktop\CIDACS_PAMACS\React\argon-dashboard-react-master\node_modules\webpack\lib\NormalModule.js
- C:\Users\andre.rocha\Desktop\CIDACS_PAMACS\React\argon-dashboard-react-master\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\andre.rocha\Desktop\CIDACS_PAMACS\React\argon-dashboard-react-master\node_modules\webpack\lib\Compiler.js
- C:\Users\andre.rocha\Desktop\CIDACS_PAMACS\React\argon-dashboard-react-master\node_modules\webpack\lib\webpack.js
- C:\Users\andre.rocha\Desktop\CIDACS_PAMACS\React\argon-dashboard-react-master\node_modules\react-scripts\scripts\start.js

---
### Solution
I don't have a solution

**Comment by TrueGeek** [comment]
Same here. TONS of errors during npm install

**Comment by einazare** [comment]
Hello there guys,

What nodejs version do you have?
Can you please make sure that you have the latest version: https://nodejs.org/en/ (12.13.1)?

Best,
Manu

**Comment by TrueGeek** [comment]
I'm on v12.1.0, that may have been the issue. I ended up downloading your other template: Light Bootstrap React Admin and it worked great!

**Comment by einazare** [comment]
Hello again,

Please make sure you have the latest node-sass version and also you have the latest LTS version of NodeJS, which at the moment is 12.13.1.
Let me know if that was the issue. 

Best,
Manu

**Comment by kimhorng** [comment]
Hello, 
I also have problem with npm start it showed

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon-dashboard-pro-react@1.0.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon-dashboard-pro-react@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kimhorng\AppData\Roaming\npm-cache\_logs\2019-11-29T19_10_26_730Z-debug.log

**Comment by einazare** [comment]
Hello there, @kimhorng 

Please make a video with the following:

* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run in terminal `node -v`
* If working on Mac: Run `npm run install:clean`
* If working on Windows: Run `npm install`
* If working on Windows: Run `npm start`
* Showcase the issue

Best,
Manu

**Comment by cai0m3ga** [comment]
I'am having the exact same problem here, just downloaded today both the project and nodeJS but i get the error bellow (also attached print):

PS C:\argon-dashboard-react-master> npm start                                                                           
> argon-dashboard-react@1.0.0 start C:\argon-dashboard-react-master
> react-scripts start
Starting the development server...
Failed to compile.

./src/assets/scss/argon-dashboard-react.scss (./node_modules/css-loader??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/assets/scss/argon-dashboard-react.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
Require stack:
- C:\argon-dashboard-react-master\node_modules\sass-loader\lib\loader.js
- C:\argon-dashboard-react-master\node_modules\loader-runner\lib\loadLoader.js
- C:\argon-dashboard-react-master\node_modules\loader-runner\lib\LoaderRunner.js
- C:\argon-dashboard-react-master\node_modules\webpack\lib\NormalModule.js
- C:\argon-dashboard-react-master\node_modules\webpack\lib\NormalModuleFactory.js
- C:\argon-dashboard-react-master\node_modules\webpack\lib\Compiler.js
- C:\argon-dashboard-react-master\node_modules\webpack\lib\webpack.js
- C:\argon-dashboard-react-master\node_modules\react-scripts\scripts\start.js

![print](https://user-images.githubusercontent.com/20325619/72950977-a9ee8e80-3d6b-11ea-8eb2-3a2baf1daa71.PNG)

My node version:

PS C:\argon-dashboard-react-master> node -v    
 v12.14.1

![print](https://user-images.githubusercontent.com/20325619/72951142-2da87b00-3d6c-11ea-9bb2-92f87dc240d4.png)

**Comment by cai0m3ga** [comment]
Guys i think i just found out how to solve this, my problem was with the "node-sass" version in the "package.json" file, i found out that the current version on the project is "4.11.0" and works with node 11.x:

[https://github.com/sass/node-sass](url)

So i changed my "node-sass" version to "4.12.0" >> deleted the "node_modules" folder >> "npm i"

Now it seens to work just fine.

![print](https://user-images.githubusercontent.com/20325619/72952645-44050580-3d71-11ea-89fe-88f7b333d8df.png)

![print](https://user-images.githubusercontent.com/20325619/72952686-66971e80-3d71-11ea-98f5-75ac896dc3dc.png)

**Comment by harikaran003** [comment]
Compiled with problems:
×
ERROR in ./src/Assets/scss/argon-dashboard-pro-react.scss?v1.2.1 (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/Assets/scss/argon-dashboard-pro-react.scss?v1.2.1)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: linear-gradient(to right, #FE932C, #F75100) is not a color.
    ╷
255 │ $link-hover-color: darken($link-color, 15%) !default;
    │                    ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  src\Assets\scss\custom\_variables.scss 255:20        @import
  src\Assets\scss\argon-dashboard-pro-react.scss 27:9  root stylesheet
