### ISSUE TITLE
Argon Design System React?

### ISSUE THREAD

**Issue by knittycatkitty** [creativetimofficial/argon-dashboard-react#2]
Hi are you guys going to create a React version of the Argon Design System?

**Comment by rmbasilio** [comment]
I would like to know this too!

**Comment by einazare** [comment]
Hello there @knittycatkitty @rmbasilio ,

Thank you for your interest in working with our products.
Yes, we are going to make a React version for this product as well.
A fair estimate would be around 3-5 weeks.

Best,
Manu
