### ISSUE TITLE
Auto rerender not available

### ISSUE THREAD

**Issue by trgkyle** [creativetimofficial/argon-dashboard-react#27]
how i can use debug with npm run start:debug ? i can't use it and i'm try npm start cannot have this auto rerender after file change ? i'm using npm test but it show error ? help me

**Comment by einazare** [comment]
Hello there, @truonghdpk ,

All the available command are here: https://demos.creative-tim.com/argon-dashboard-react/#/documentation/build-tools
As you will see, we do not offer support for `start:debug` command.
I will leave this issue open, maybe somebody will come to your help, if not, in about 20 to 30 days, I will close it.

Best,
Manu
