### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by joelsynth** [creativetimofficial/argon-dashboard-react#29]
Good afternoon, I follow all the steps but I can't manage to run the app with node and visual studio code. I leave you a screen cap.
Thank you

![image](https://user-images.githubusercontent.com/31223940/77197129-62625580-6ac3-11ea-9171-225cf9275441.png)

The error that appears to me is the following:

./node_modules/react-dev-utils/webpackHotDevClient.js
Error: [BABEL] C:\Users\Turco\Documents\argon3\node_modules\react-dev-utils\webpackHotDevClient.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "C:\\Users\\Turco\\Documents\\argon3\\node_modules\\babel-preset-react-app\\dependencies.js$0")
    at Array.map (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)

**Comment by einazare** [comment]
Hello there,

Please try changing react-scripts to 3.4.0.

Best,
Manu

**Comment by sshtel** [comment]
react-scripts:3.4.0 works for me
