### ISSUE TITLE
Next.js

### ISSUE THREAD

**Issue by john916zhang** [creativetimofficial/argon-dashboard-react#35]
Thanks for this wonderful template.

Is it possible to use this template with Next.js? 

Thanks.

**Comment by einazare** [comment]
Hello there, @anderson916 ,

Thank you for your interest in working with our products.
This product does not come with NextJS support out of the box, so you will have to do the changes yourself.

Best,
Manu

**Comment by einazare** [comment]
Hello there, @john916zhang ,

We've launched a NextJS version for this product. Please check it out here: https://www.creative-tim.com/product/nextjs-argon-dashboard

Best,
Manu
