### ISSUE TITLE
[Bug] Looking for a guide to properly integrate this into a Rails 6 Application

### ISSUE THREAD

**Issue by single-stop-rj** [creativetimofficial/argon-dashboard-react#37]
### Version
1.0.0
### Reproduction link
https://nolink.com
### Operating System
Mac OS
### Device
Macbook Pro
### Browser & Version
Chrome lastest
### Steps to reproduce
I guess Im just looking for some help with installing this into a rails app. 
### What is expected?
it works with rails. 
### What is actually happening?
Im no css master. its quite effed up 

---

**Comment by einazare** [comment]
Hello there, @single-stop-rj ,

Thank you for your interest in working with our products, right now, we do not offer support for third party plugins or integration.
For this, please refer to our custom development team here: [https://services.creative-tim.com/](https://services.creative-tim.com/?ref=ct-footer)

Best,
Manu
