### ISSUE TITLE
Error when starting apps (build success)

### ISSUE THREAD

**Issue by difaananda40** [creativetimofficial/argon-dashboard-react#4]
I have a problem, build success without error but when starting apps, it didnt show anything and some error in console.

![wew2](https://user-images.githubusercontent.com/32413048/59989272-fb695a80-9670-11e9-8204-c068a7315e18.png)

**Comment by einazare** [comment]
dupe https://github.com/creativetimofficial/argon-dashboard-react/issues/3

also, invalid since our issue template was not used to open this issue:

```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/argon-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->

```
