### ISSUE TITLE
[Bug] Template will crash on TypeError

### ISSUE THREAD

**Issue by Singtah** [creativetimofficial/argon-dashboard-react#48]
### Version
1.1.0
### Reproduction link
https://github.com/creativetimofficial/argon-dashboard-react
### Operating System
Ubuntu WSL
### Device
Desktop
### Browser & Version
Brave 1.17.75
### Steps to reproduce
Run in terminal
`npm install`
Then run
`npm start`

Compiles successfully, go to localhost:3000, displays the following error message :

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
```
### What is expected?
template should be displayed
### What is actually happening?
Error message displayed in browser

---

**Comment by einazare** [comment]
Hello there, @Singtah ,

This issue has been solved here: https://github.com/creativetimofficial/argon-dashboard-react/issues/23
In about 1-2 months we'll update the product and solve it in the download zip as well.
I will close this issue, as this is a duplicate.

Best,
Manu
