### ISSUE TITLE
[Bug] Error when starting apps (build success)

### ISSUE THREAD

**Issue by difaananda40** [creativetimofficial/argon-dashboard-react#5]
### Version
1.0.0
### Reproduction link
https://imgur.com/X7k7KUc
### Steps to reproduce
1. Running `npm run build`
2. Running the apps using `serve -s build`
3. App will run in browser, but it didnt show anything, and error appears on console.
(i'm using default argon template)
### What is expected?
Apps running smoothly
### What is actually happening?
App didnt show anything

---

**Comment by einazare** [comment]
Hello there, @difaananda40 ,

Thank you for using our issue template, but this is a duplicate issue.
Please read the following thread, the solution is found in one of my comments: [argon-dashboard-react issue 3](https://github.com/creativetimofficial/argon-dashboard-react/issues/3)

Best,
Manu
