### ISSUE TITLE
[Bug] The documentation page is not working

### ISSUE THREAD

**Issue by javiio** [creativetimofficial/argon-dashboard-react#54]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-react/#/documentation/overview
### Operating System
Mac
### Device
Mac
### Browser & Version
Chrome
### Steps to reproduce
1. Go to https://demos.creative-tim.com/argon-dashboard-pro-react/#/documentation/overview
2. It does not display the documentation but a landing page
### What is expected?
Show the docs
### What is actually happening?
Redirecting to the landing

---

**Comment by einazare** [comment]
Hello there, @grissproject ,

I've just solved the issue. Thanks for letting us know!

Best,
Manu
