### ISSUE TITLE
[Help Wanted] form filter fields based in select field input

### ISSUE THREAD

**Issue by Ashjoker24** [creativetimofficial/argon-dashboard-react#55]
I am new for react and now I am adding a form to get host credentials like below I want to set conditions by choosing the "authentication type" field in my form How can I set that??

<label for="ipaddressInput">Ip or DNS</label>
                      <input type="text" id="ipaddressInput" className="form-control" placeholder="Enter Your ip or dns here" />
                      <br />
                      <label for="userInputName">User Name</label>
                      <input type="text" id="userInputName" className="form-control" placeholder="Enter Your username here" />
                      <br />
                      <label for="Selectmethod">Authentication Method</label>
                      <select className="form-control" placeholder="Search to Select" name="auth_method"  >
                        <option>-- Search to Select --</option>
                        <option value="password">Password</option>
                        <option value="ssh">SSH Key</option>
                      </select>

                      <label for="userInputName">Password</label>
                      <input type="text" id="passwordInputName" className="form-control" placeholder="Enter Your Host password here" />
                      <br />
                      <label for="userInputName">SSH-Key</label>
                      <input type="textarea" id="ssh_keyInputName" className="form-control" placeholder="SSH-Key" />
                      <br />

**Comment by einazare** [comment]
Hello there, @Ashjoker24 ,

We're sorry, but this is not an enhancement, this is help-wanted.
We'll change and edit the issue accordingly. We'll leave it open for around 30 days, maybe someone from our community will come to your help.

Best,
Manu

**Comment by Ashjoker24** [comment]
Finally, I found a way to do a modal with this template in react
