### ISSUE TITLE
Fast Clicks in Sidebar Menu

### ISSUE THREAD

**Issue by SereiaMaster** [creativetimofficial/argon-dashboard-react#57]
### Version
Argon Dashboard React - v1.1.0
### Reproduction link
https://Idontknowdothis.com.br
### Operating System
Windows
### Device
Desktop and Mobile
### Browser & Version
Chrome and Firefox
### Steps to reproduce
1 Click in any link in sidebar
2 Click another link very fast
3 Repeat again in another link
### What is expected?
Change page normaly
### What is actually happening?
Pages moving and bugging repeatedly

---

**Comment by einazare** [comment]
Hello there, @SereiaMaster ,

We've tested the product, and it seems to us that it is working as expected - tests were made on our live preview here: https://demos.creative-tim.com/argon-dashboard-react/#/admin/index
Please provide us with the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

Best,
Manu

PS: The link you have provided redirects us to a `This site can’t be reached` website. Please, next time when you open a Github Issue, give us a link relevant to the product at hand, for example, the live preview of the product (in this case https://demos.creative-tim.com/argon-dashboard-react/#/admin/index), if not, we will be forced to close and ignore your issue.
<img width="957" alt="Screen Shot 2021-03-17 at 10 11 52 AM" src="https://user-images.githubusercontent.com/26245512/111435253-39da5f00-8709-11eb-8ad7-629a719d211b.png">
