### ISSUE TITLE
[Bug] Could not resolve dependency:

### ISSUE THREAD

**Issue by jcbolor** [creativetimofficial/argon-dashboard-react#59]
### Version
1.2.0
### Reproduction link
http://na.na
### Operating System
linux mint
### Device
laptop
### Browser & Version
na
### Steps to reproduce
git clone from repo
npm install
### What is expected?
success installation
### What is actually happening?
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: argon-dashboard-react@1.2.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0" from react-datetime@3.0.4
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"^3.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

---
### Solution
added --force

**Comment by sajadevo** [comment]
**Hi**
Thanks for using our products, we just solve this issue its a problem with NodeJS version you have to download the NodeJS LTS version and it will fix the problem.

**All the best**
**Sajad**

**Comment by maiestro21** [comment]
Encountered the same issue.
Had some headache until finding this issue.

Sadly the --force did not work for me. 

I reinstalled the LTS version from official source and looks good now.

Thanks @sajadevo for solution.
