### ISSUE TITLE
[Bug] npm not install

### ISSUE THREAD

**Issue by UmangD85** [creativetimofficial/argon-dashboard-react#67]
### Version
1.2.1
### Reproduction link
https://github.com/creativetimofficial/argon-dashboard-react
### Operating System
Windows
### Device
Lenovo
### Browser & Version
Chrome
### Steps to reproduce
Download code from this link : https://github.com/creativetimofficial/argon-dashboard-react

go to project folder & run npm install, 
its not working properly.

my node version is 14.16.1
### What is expected?
install & run properly
### What is actually happening?
not install

---

**Comment by lucasdiedrich** [comment]
Yeap, it this seems a problem. Using npm i --force ignores this to run the project.
![image](https://user-images.githubusercontent.com/817482/127586265-38d9f54d-ef75-454c-a97d-5c87aac88c1e.png)

The error on npm i sugests a incompatibility with: 
![image](https://user-images.githubusercontent.com/817482/127586323-e74c9600-9efa-4564-bf28-93090888430d.png)

**Comment by UmangD85** [comment]
Hello @lucasdiedrich,

Thanks for your time.

im downgrade the version of react-datetime to 3.0.3 & try command npm install but its not working & then im go with npm install --force but im having none or more issues with this, 

attach a log file for your reference. & my Node version is 16.4.1
Thank You,

[2021-07-30T18_49_28_686Z-debug.log](https://github.com/creativetimofficial/argon-dashboard-react/files/6909507/2021-07-30T18_49_28_686Z-debug.log)

**Comment by Klausmd5** [comment]
> Hello @lucasdiedrich,
> 
> Thanks for your time.
> 
> im downgrade the version of react-datetime to 3.0.3 & try command npm install but its not working & then im go with npm install --force but im having none or more issues with this,
> 
> attach a log file for your reference. & my Node version is 16.4.1
> Thank You,
> 
> [2021-07-30T18_49_28_686Z-debug.log](https://github.com/creativetimofficial/argon-dashboard-react/files/6909507/2021-07-30T18_49_28_686Z-debug.log)


same here

**Comment by Klausmd5** [comment]
Got it working!

Here is what I did:

- Install node ltd (I don't think that this solved it..)
- Modified package.json and replaced fontawsome dependency with `"@fortawesome/fontawesome-free": "^5.15.4",`
- use yarn install (I also don't think that this helped a lot)

It seems that fontawsome had some api changes for the free api so you can't really download older versions without premium.

**Comment by spacjar** [comment]
Somehow got it working.

### This is what I did:
1. Go to **package.json** and **remove** the following:
```   
"node-sass": "6.0.1",
"node-sass-package-importer": "5.3.2",
```
2. Install all dependencies from package.json (you may need to use --force)
`npm install --force`
3. Replace node-sass with sass 
`npm install sass`
4. Start your development server
`npm start`

### Note
It may also be worth looking at your Node version and comparing it with minimum and maximum supported versions of node-sass. More info here: https://www.npmjs.com/package/node-sass
