### ISSUE TITLE
Problem with sass imports

### ISSUE THREAD

**Issue by angarc** [creativetimofficial/argon-dashboard-react#9]
I'm using webpack to install argon-dashboard. Here is how I'm importing styles:

`@import '@creative-tim-official/argon-dashboard-free/assets/scss/argon';`

This is the error I'm getting: 

```
Error: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import "custom/alert";
^
      File to import not found or unreadable: custom/alert.
```

I didn't specify what version to use when I ran `yarn add` so I'm pretty sure I have the latest version. I'm a little new to Yarn. Any help is appreciated!

**Comment by einazare** [comment]
The issue is being closed due to the fact that you haven't used our issue template:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/argon-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```
Please note this line from the issue template:
**If your issue was not created using the app above, it will be closed immediately.**

Really sorry about this, but my manager doesn't allow me to solve issues that do not follow our rules.

**Comment by angarc** [comment]
@EINazare Omg, I just read the name of the github repo. I'm in the wrong place. Sorry, that was a really stupid mistake lol. I meant to post this the `argon-dashboard` repo, not the `argon-dashboard-react` repo. I'll post my new issue there.
